[package]
name = "quake-render"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
quake-asset = { path = "../quake-asset" }

anyhow.workspace = true

wgpu = "28.0.0"
pollster = "0.4.0"
