[package]
name = "quake-input"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true

indexmap = "2.13.0"
toml = "0.9.10"
serde = { version = "1.0.228", features = ["derive"] }
