[package]
name = "quake-audio"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
quake-asset = { path = "../quake-asset" }

anyhow.workspace = true

kira = "0.11.0"
